# general
seed: 1
device: 'cuda'
output_path: 'PNP-results/1_0'

# data
image_path: 'data/1_0.png'
latents_path: 'latents_forward'

directory: 'data2'

# diffusion
sd_version: '1.5'
guidance_scale: 7.5
n_timesteps: 50
prompt: ''
negative_prompt: ''

# pnp injection thresholds, ∈ [0, 1]
pnp_attn_t: 0.5
pnp_f_t: 0.8
